/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.transaction.create.Request.Raw,
    FlagrightApi.TransactionEvent
> = core.serialization.lazyObject(async () => (await import("../../..")).TransactionEvent);

export declare namespace Request {
    type Raw = serializers.TransactionEvent.Raw;
}

export const Response: core.serialization.Schema<
    serializers.transaction.create.Response.Raw,
    FlagrightApi.TransactionEventMonitoringResult
> = core.serialization.lazyObject(async () => (await import("../../..")).TransactionEventMonitoringResult);

export declare namespace Response {
    type Raw = serializers.TransactionEventMonitoringResult.Raw;
}
