/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.transaction.retrieve.Response.Raw,
    FlagrightApi.TransactionWithRulesResult
> = core.serialization.lazyObject(async () => (await import("../../..")).TransactionWithRulesResult);

export declare namespace Response {
    type Raw = serializers.TransactionWithRulesResult.Raw;
}
