/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.transaction.verify.Request.Raw, FlagrightApi.Transaction> =
    core.serialization.lazyObject(async () => (await import("../../..")).Transaction);

export declare namespace Request {
    type Raw = serializers.Transaction.Raw;
}

export const Response: core.serialization.Schema<
    serializers.transaction.verify.Response.Raw,
    FlagrightApi.TransactionMonitoringResult
> = core.serialization.lazyObject(async () => (await import("../../..")).TransactionMonitoringResult);

export declare namespace Response {
    type Raw = serializers.TransactionMonitoringResult.Raw;
}
