/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for amount
 */
export interface Amount {
    amountValue: number;
    amountCurrency: FlagrightApi.CurrencyCode;
}
