/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Model for device data
 */
export interface DeviceData {
    batteryLevel?: number;
    deviceLatitude?: number;
    deviceLongitude?: number;
    ipAddress?: string;
    deviceIdentifier?: string;
    vpnUsed?: boolean;
    operatingSystem?: string;
    deviceMaker?: string;
    deviceModel?: string;
    deviceYear?: string;
    appVersion?: string;
}
