/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for list of executed rules
 */
export interface ExecutedRulesResult {
    ruleId: string;
    ruleInstanceId: string;
    ruleName: string;
    ruleDescription: string;
    ruleAction: FlagrightApi.RuleAction;
    ruleHit: boolean;
    ruleHitMeta?: FlagrightApi.RuleHitMeta;
}
