/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

export interface PaymentMethodLimits {
    ach?: FlagrightApi.TransactionLimit;
    card?: FlagrightApi.TransactionLimit;
    iban?: FlagrightApi.TransactionLimit;
    upi?: FlagrightApi.TransactionLimit;
    genericBankAccount?: FlagrightApi.TransactionLimit;
    mpesa?: FlagrightApi.TransactionLimit;
    swift?: FlagrightApi.TransactionLimit;
    wallet?: FlagrightApi.TransactionLimit;
    check?: FlagrightApi.TransactionLimit;
}
