/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Details of rule execution, for internal purposes only
 */
export interface RuleHitMeta {
    hitDirections?: FlagrightApi.RuleHitDirection[];
    caseCreationType?: FlagrightApi.CaseCreationType;
    falsePositiveDetails?: FlagrightApi.FalsePositiveDetails;
}
