/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for transaction additional payload
 */
export interface TransactionUpdatable {
    transactionState?: FlagrightApi.TransactionState;
    originAmountDetails?: FlagrightApi.TransactionAmountDetails;
    destinationAmountDetails?: FlagrightApi.TransactionAmountDetails;
    relatedTransactionIds?: string[];
    productType?: string;
    promotionCodeUsed?: boolean;
    reference?: string;
    deviceData?: FlagrightApi.DeviceData;
    tags?: FlagrightApi.Tag[];
}
