/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

export interface TransactionAmountLimit {
    day?: FlagrightApi.Amount;
    week?: FlagrightApi.Amount;
    month?: FlagrightApi.Amount;
    year?: FlagrightApi.Amount;
}
