/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for transaction limits for a given user
 */
export interface TransactionLimits {
    maximumDailyTransactionLimit?: FlagrightApi.Amount;
    maximumWeeklyTransactionLimit?: FlagrightApi.Amount;
    maximumMonthlyTransactionLimit?: FlagrightApi.Amount;
    maximumQuarterlyTransactionLimit?: FlagrightApi.Amount;
    maximumTransactionLimit?: FlagrightApi.Amount;
    maximumYearlyTransactionLimit?: FlagrightApi.Amount;
    paymentMethodLimits?: FlagrightApi.PaymentMethodLimits;
}
