/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for transaction payload with rules result
 */
export interface TransactionWithRulesResult extends FlagrightApi.Transaction {
    executedRules: FlagrightApi.ExecutedRulesResult[];
    hitRules: FlagrightApi.HitRulesDetails[];
}
