/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for transaction-related events
 */
export interface TransactionEvent {
    transactionState: FlagrightApi.TransactionState;
    timestamp: number;
    /** Transaction ID the event pertains to */
    transactionId: string;
    /** Unique event ID */
    eventId?: string;
    /** Reason for the event or a state change */
    reason?: string;
    /** Event description */
    eventDescription?: string;
    updatedTransactionAttributes?: FlagrightApi.TransactionUpdatable;
    metaData?: FlagrightApi.DeviceData;
}
