/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

export interface Transaction extends FlagrightApi.TransactionBase, FlagrightApi.TransactionUpdatable {}
