/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model to convey the results of transaction monitoring
 */
export interface TransactionMonitoringResult extends FlagrightApi.RulesResults {
    transactionId: string;
}
