/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.consumerUser.createEvent.Request.Raw,
    FlagrightApi.ConsumerUserEvent
> = core.serialization.lazyObject(async () => (await import("../../..")).ConsumerUserEvent);

export declare namespace Request {
    type Raw = serializers.ConsumerUserEvent.Raw;
}

export const Response: core.serialization.Schema<serializers.consumerUser.createEvent.Response.Raw, FlagrightApi.User> =
    core.serialization.lazyObject(async () => (await import("../../..")).User);

export declare namespace Response {
    type Raw = serializers.User.Raw;
}
