/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.consumerUser.retrieve.Response.Raw, FlagrightApi.User> =
    core.serialization.lazyObject(async () => (await import("../../..")).User);

export declare namespace Response {
    type Raw = serializers.User.Raw;
}
