/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class FlagrightApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, FlagrightApiTimeoutError.prototype);
    }
}
