/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const TransactionLimit: core.serialization.ObjectSchema<
    serializers.TransactionLimit.Raw,
    FlagrightApi.TransactionLimit
> = core.serialization.object({
    transactionCountLimit: core.serialization
        .lazyObject(async () => (await import("../../..")).TransactionCountLimit)
        .optional(),
    transactionAmountLimit: core.serialization
        .lazyObject(async () => (await import("../../..")).TransactionAmountLimit)
        .optional(),
    averageTransactionAmountLimit: core.serialization
        .lazyObject(async () => (await import("../../..")).TransactionAmountLimit)
        .optional(),
});

export declare namespace TransactionLimit {
    interface Raw {
        transactionCountLimit?: serializers.TransactionCountLimit.Raw | null;
        transactionAmountLimit?: serializers.TransactionAmountLimit.Raw | null;
        averageTransactionAmountLimit?: serializers.TransactionAmountLimit.Raw | null;
    }
}
