/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<serializers.businessUser.create.Request.Raw, FlagrightApi.Business> =
    core.serialization.lazyObject(async () => (await import("../../..")).Business);

export declare namespace Request {
    type Raw = serializers.Business.Raw;
}

export const Response: core.serialization.Schema<
    serializers.businessUser.create.Response.Raw,
    FlagrightApi.CreateBusinessUserResponse
> = core.serialization.lazyObject(async () => (await import("../../..")).CreateBusinessUserResponse);

export declare namespace Response {
    type Raw = serializers.CreateBusinessUserResponse.Raw;
}
