/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.businessUser.createEvent.Request.Raw,
    FlagrightApi.BusinessUserEvent
> = core.serialization.lazy(async () => (await import("../../..")).BusinessUserEvent);

export declare namespace Request {
    type Raw = serializers.BusinessUserEvent.Raw;
}

export const Response: core.serialization.Schema<
    serializers.businessUser.createEvent.Response.Raw,
    FlagrightApi.Business
> = core.serialization.lazyObject(async () => (await import("../../..")).Business);

export declare namespace Response {
    type Raw = serializers.Business.Raw;
}
