/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.businessUser.retrieve.Response.Raw,
    FlagrightApi.Business
> = core.serialization.lazyObject(async () => (await import("../../..")).Business);

export declare namespace Response {
    type Raw = serializers.Business.Raw;
}
