/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for business user-related events
 */
export interface BusinessUserEvent {
    timestamp: number;
    userId: string;
    eventId?: string;
    reason?: string;
    eventDescription?: string;
    updatedBusinessUserAttributes?: FlagrightApi.BusinessOptional;
}
