/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for a business user base fields
 */
export interface BusinessBase {
    userId: string;
    legalEntity: FlagrightApi.LegalEntity;
    createdTimestamp: number;
    riskLevel?: FlagrightApi.RiskLevel;
}
