/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for business user company registration details
 */
export interface CompanyRegistrationDetails {
    registrationIdentifier: string;
    registrationCountry: FlagrightApi.CountryCode;
    taxIdentifier?: string;
    legalEntityType?: string;
    dateOfRegistration?: string;
    tags?: FlagrightApi.Tag[];
}
