/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for business user legal entity details
 */
export interface LegalEntity {
    companyGeneralDetails: FlagrightApi.CompanyGeneralDetails;
    companyFinancialDetails?: FlagrightApi.CompanyFinancialDetails;
    companyRegistrationDetails?: FlagrightApi.CompanyRegistrationDetails;
    reasonForAccountOpening?: string[];
    contactDetails?: FlagrightApi.ContactDetails;
}
