/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for a generic individual - different from User model by not having userId field
 */
export interface Person {
    generalDetails: FlagrightApi.UserDetails;
    legalDocuments?: FlagrightApi.LegalDocument[];
    contactDetails?: FlagrightApi.ContactDetails;
    pepStatus?: FlagrightApi.PepStatus[];
    tags?: FlagrightApi.Tag[];
}
