/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const BusinessBase: core.serialization.ObjectSchema<serializers.BusinessBase.Raw, FlagrightApi.BusinessBase> =
    core.serialization.object({
        userId: core.serialization.string(),
        legalEntity: core.serialization.lazyObject(async () => (await import("../../..")).LegalEntity),
        createdTimestamp: core.serialization.number(),
        riskLevel: core.serialization.lazy(async () => (await import("../../..")).RiskLevel).optional(),
    });

export declare namespace BusinessBase {
    interface Raw {
        userId: string;
        legalEntity: serializers.LegalEntity.Raw;
        createdTimestamp: number;
        riskLevel?: serializers.RiskLevel.Raw | null;
    }
}
