/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const BusinessUserEvent: core.serialization.Schema<
    serializers.BusinessUserEvent.Raw,
    FlagrightApi.BusinessUserEvent
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace BusinessUserEvent {
    type Raw = Record<string, unknown>;
}
