/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for standardized address
 */
export interface Address {
    addressLines: unknown[];
    postcode: string;
    city: string;
    state?: string;
    country: string;
    tags?: FlagrightApi.Tag[];
}
