/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Model for a generic consumer name
 */
export interface ConsumerName {
    firstName: string;
    middleName?: string;
    lastName?: string;
}
