/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

export interface KycStatusDetails {
    reason?: string;
    status?: FlagrightApi.KycStatus;
}
