/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Generic key-value pair model to append a custom variable being sent to Flagright API
 */
export interface Tag {
    key: string;
    value: string;
}
