/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

export interface UserStateDetails {
    userId?: string;
    reason?: string;
    state: FlagrightApi.UserState;
}
