/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { FlagrightApi } from "@fern-api/flagright";
import * as core from "../../../../core";

export const KycStatus: core.serialization.Schema<serializers.KycStatus.Raw, FlagrightApi.KycStatus> =
    core.serialization.enum_(["SUCCESSFUL", "FAILED", "NOT_STARTED", "IN_PROGRESS", "MANUAL_REVIEW"]);

export declare namespace KycStatus {
    type Raw = "SUCCESSFUL" | "FAILED" | "NOT_STARTED" | "IN_PROGRESS" | "MANUAL_REVIEW";
}
