/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for consumer user-related events
 */
export interface ConsumerUserEvent {
    timestamp: number;
    userId: string;
    eventId?: string;
    reason?: string;
    eventDescription?: string;
    updatedConsumerUserAttributes?: FlagrightApi.UserOptional;
}
