/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for User details
 */
export interface UserOptional {
    userStateDetails?: FlagrightApi.UserStateDetails;
    kycStatusDetails?: FlagrightApi.KycStatusDetails;
    legalDocuments?: FlagrightApi.LegalDocument[];
    contactDetails?: FlagrightApi.ContactDetails;
    transactionLimits?: FlagrightApi.TransactionLimits;
    riskLevel?: FlagrightApi.RiskLevel;
    reasonForAccountOpening?: string[];
    pepStatus?: FlagrightApi.PepStatus[];
    tags?: FlagrightApi.Tag[];
}
