/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { FlagrightApi } from "@fern-api/flagright";

/**
 * Model for consumer user personal details
 */
export interface UserDetails {
    name: FlagrightApi.ConsumerName;
    dateOfBirth?: string;
    countryOfResidence?: FlagrightApi.CountryCode;
    countryOfNationality?: FlagrightApi.CountryCode;
}
